# Generated by Django 5.1.6 on 2025-07-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kitap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255)),
                ('yazar', models.CharField(max_length=255)),
                ('aciklama', models.TextField()),
                ('yayin_tarihi', models.DateField()),
                ('kategori', models.CharField(choices=[('roman', 'Roman'), ('hikaye', 'Hikaye')], max_length=20)),
                ('kapak_resmi', models.ImageField(blank=True, null=True, upload_to='kapaklar/')),
            ],
        ),
    ]
