# Generated by Django 5.1.6 on 2025-08-30 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitaplar', '0002_author_book_delete_kitap'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
