services:
  - type: web
    name: swipebooks-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn kitapprojesi.wsgi:application"
    autoDeploy: true
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: kitapprojesi.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: swipebooks-backend.onrender.com
